- .github/workflows/ci.yml
- https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
> replaced deprecating command - set-output

- app/channels/intervention_channel.rb
- app/models/intervention.rb
- spec/channels/intervention_channel_spec.rb
- [CIAS-3422](https://htdevelopers.atlassian.net/browse/CIAS30-3422)
- [CIAS-3420](https://htdevelopers.atlassian.net/browse/CIAS30-3420)
- broadcast message when sb leaves the channel
- fix issue when `left_joins` create duplicated user's rows
> [CIAS30-3422][CIAS30-3420] too many notifications after leaving the channel + Editing is not stopped on channel unsubscribe

- app/channels/intervention_channel.rb
- app/controllers/v1/interventions_controller.rb
- spec/channels/intervention_channel_spec.rb
- [CIAS-3431](https://htdevelopers.atlassian.net/browse/CIAS30-3431)
- removed check if intervention is published. Thanks to that, we can assign the current editor to the published intervention and edit for example the status (from `published` to `archived`) 
- added two simple tests to cover changes
- small refactor `interventions#update`
> [CIAS30-3431] enable entering edit mode for a published intervention

- app/controllers/v1/live_chat/interventions/files_controller.rb
- app/controllers/v1/live_chat/interventions/links_controller.rb
- app/controllers/v1/live_chat/interventions/navigator_setups_controller.rb
- app/controllers/v1/live_chat/interventions/navigators_controller.rb
- app/controllers/v1/live_chat/navigators/invitations_controller.rb
- spec/requests/v1/live_chat/interventions/navigator_invitations/create_spec.rb
- spec/requests/v1/live_chat/interventions/navigator_invitations/destroy_spec.rb
- spec/requests/v1/live_chat/interventions/navigator_setup/update_spec.rb
- spec/requests/v1/live_chat/interventions/navigators/create_spec.rb
- spec/requests/v1/live_chat/interventions/navigators/destroy_spec.rb
- spec/requests/v1/live_chat/interventions/participant_links/create_spec.rb
- spec/requests/v1/live_chat/interventions/participant_links/destroy_spec.rb
- spec/requests/v1/live_chat/interventions/participant_links/update_spec.rb
- [CIAS-3430](https://htdevelopers.atlassian.net/browse/CIAS30-3430)
- added check to all live chat controllers which return `forbidden` if the current user isn't a current editor 
- added tests to cover new parts of the code
> [CIAS30-3430] User can edit navigator settings without being current editor

- app/finders/user_finder.rb
- spec/requests/v1/users/researchers_spec.rb
- [CIAS-3434](https://htdevelopers.atlassian.net/browse/CIAS30-3434)
- when sg fetching visible for him researcher, ignore him from this list
- updated tests to meet the criteria
> [CIAS30-3434] Don't return current user when fetching researchers by e-intervention admin

- app/controllers/v1/interventions/logos_controller.rb
- spec/requests/v1/interventions/logos/create_spec.rb
- spec/requests/v1/interventions/logos/destroy_spec.rb
- spec/requests/v1/interventions/logos/update_spec.rb
- [CIAS-3425](https://htdevelopers.atlassian.net/browse/CIAS30-3425)
- block the ability to manage a logo beyond the current editor 
- add tests to cover new part of code
> [CIAS30-3425] block the ability to manage a logo beyond the current editor

- app/controllers/v1/interventions_controller.rb
- app/models/concerns/clone.rb
- spec/jobs/clone_jobs/intervention_spec.rb
- spec/models/intervention_spec.rb
- spec/requests/v1/interventions/clone_spec.rb
- [CIAS-3415](https://htdevelopers.atlassian.net/browse/CIAS30-3415)
- accept `emails` instead of `user_ids`
- remove unused `let`
> [CIAS30-3415] adjust endpoint to clone to accept emails instead of user_ids

- app/models/question/number.rb
- spec/requests/v1/questions/create_spec.rb
- [CIAS-3403](https://htdevelopers.atlassian.net/browse/CIAS30-3403)
- when creating a new numeric question, add two additional parameters -> `max_length` and `min_length`
> [CIAS30-3403] add default values to settings in the number question 

- app/models/ability/e_intervention_admin.rb
- spec/abilities/report_templates_spec.rb
- spec/abilities/sessions_spec.rb
- spec/abilities/sms_plans_spec.rb
- [CIAS-3439](https://htdevelopers.atlassian.net/browse/CIAS30-3439)
- added missing rules to e-int admin's ability(among others: fetch report templates, sms-es, sessions)
- added some tests to cover this case
> [CIAS30-3439] Handle e-intervention admin accesses to interventions in their organization

- app/channels/intervention_channel.rb
- spec/channels/intervention_channel_spec.rb
- [CIAS-3468](https://htdevelopers.atlassian.net/browse/CIAS30-3468)
- allow all with at least view access to the intervention to connect to the InterventionChannel
> [CIAS30-3468] allow all with at least view access to the intervention to connect to the InterventionChannel

- app/models/collaborator.rb
- config/locales/en.yml
- spec/requests/v1/interventions/collaborators/create_spec.rb
- [CIAS-3494](https://htdevelopers.atlassian.net/browse/CIAS30-3494)
- replace the default error msg with `Validation failed: User is already a collaborator in this intervention`
> [CIAS30-3494] customize error message

- config/locales/en.yml
- [CIAS-3505](https://htdevelopers.atlassian.net/browse/CIAS30-3505)
- Added the info about the first and last name in the error message
> [CIAS30-3505]: Adjust the error message, so it will not only mention the T&C and Privacy Policy, but also a First/Last name 

- app/jobs/clone_jobs/session.rb
- app/models/concerns/clone/session.rb
- spec/jobs/clone_jobs/session_spec.rb
- spec/jobs/duplicate_jobs/session_spec.rb
- [CIAS-3384](https://htdevelopers.atlassian.net/browse/CIAS30-3384)
- formulas and `days_after_date_variable_name` for session will only get cleaned when a session is shared internally to a different intervention
- when copying a whole intervention, or when cloning a session into the same intervention, these values will be kept
> Cias30 3384

- app/channels/intervention_channel.rb
- [CIAS-3523](https://htdevelopers.atlassian.net/browse/CIAS30-2523)
- In Action Cable, you cannot directly use url_for like you would in a typical Rails controller or view context. This is because Action Cable operates on WebSocket connections, which do not have a direct HTTP request/response cycle, and therefore don't have access to routing helpers like url_for.
> [CIAS30-3523] different way to generate url in Channel

- app/channels/intervention_channel.rb
- [CIAS-3523](https://htdevelopers.atlassian.net/browse/CIAS30-3523)
- In Action Cable, you cannot directly use url_for like you would in a typical Rails controller or view context. This is because Action Cable operates on WebSocket connections, which do not have a direct HTTP request/response cycle, and therefore don't have access to routing helpers like url_for.
> different way to generate url in Channel

- config/locales/en.yml
- [CIAS-3522](https://htdevelopers.atlassian.net/browse/CIAS30-3522)
- When an invited registered user collaborates, the email link should directly redirect non-logged-in users to the login page
- changed the link in en.yml
> [CIAS30-3522] move non-registered participants to login-page

- app/controllers/v1/user_sessions_controller.rb
- app/services/v1/user_sessions/fetch_service.rb
- spec/requests/v1/user_sessions/show_spec.rb
- [CIAS-3538](https://htdevelopers.atlassian.net/browse/CIAS30-3538)
- Status change only after the response is returned
> [CIAS-3538] change the status after rendering a response

- app/services/v1/user_sessions/create_service.rb
- spec/services/v1/user_sessions/create_service_spec.rb
- [CIAS-3540](https://htdevelopers.atlassian.net/browse/CIAS30-3540)
- The creation of a session user is a clear indication that the intervention has begun. The presented situation should be mapped with the correct status. Therefore, after creating a user session, the status is set to "in_progress".
> [CIAS30-3540] change the status of the user intervention after creating a user session

- app/models/concerns/clone/intervention.rb
- app/serializers/v1/intervention_serializer.rb
- app/serializers/v1/simple_intervention_serializer.rb
- db/migrate/20230804104852_add_cleared_flag_for_intervention.rb
- db/schema.rb
- spec/factories/interventions.rb
- spec/models/intervention_spec.rb
- [CIAS-3535](https://htdevelopers.atlassian.net/browse/CIAS30-3535)
- `Intervention` now has a new flag `cleared`, by default set to `false`
> [CIAS30-3535] add a flag to intervention to check whether it was cleared

- spec/requests/v1/report_templates/delete_custom_logo_spec.rb
- spec/requests/v1/report_templates/delete_logo_spec.rb
- spec/support/shared_examples/deleting_attachment.rb
- [CIAS-3551](https://htdevelopers.atlassian.net/browse/CIAS30-3551)
- The shared example groups for deleting attachments are now used both for removing report template logo and custom cover page logo
> [CIAS30-3551] refactor the tests for deleting report logos (extract shared examples)

- app/controllers/v1/sessions/report_templates_controller.rb
- app/models/concerns/clone/report_template.rb
- spec/models/report_template_spec.rb
- spec/requests/v1/report_templates/duplicate_spec.rb
- [CIAS-3568](https://htdevelopers.atlassian.net/browse/CIAS30-3568)
- [CIAS-3569](https://htdevelopers.atlassian.net/browse/CIAS30-3569)
- The flag wasn't saved into the DB 
- removed the restriction that a researcher can't duplicate internally any report template to the session in another intervention with collaborators
> [CIAS30-3568][CIAS30-3569] fixed bug with flag and removed restriction

- app/channels/notification_channel.rb
- [CIAS-3605](https://htdevelopers.atlassian.net/browse/CIAS30-3605)
- Broadcast message on the correct stream, `navigators_in_intervention_channel_` instead of `intervention_channel_`
> [CIAS30-3605] broadcast message on the correct stream

- db/migrate/20230829180239_remove_constraint_about_user_id_from_chart_statistics.rb
- db/schema.rb
- [CIAS-3617](https://htdevelopers.atlassian.net/browse/CIAS30-3617)
- in the DB on the staging, we have some cases when we have guest users without any user session but have some chart statistics. In the model, we have set `has_many :chart_statistics, dependent: :nullify` which after calling `delete_quest_users_without_any_intervention!` in `DataClearJobs::ClearUserData` we have tried to put null in the chart statistic but in the schema we have defined that null isn't allowed
> [CIAS30-3617] Scheduled deletion job is started once again when the time of deletion come

- app/models/intervention.rb
- spec/requests/v1/interventions/index_spec.rb
- [CIAS-3574](https://htdevelopers.atlassian.net/browse/CIAS30-3574)
- added new param for `v1/interventions` - `starred`
- having it defined will only return interventions starred by the current user
> [CIAS30-3574] add filtering interventions by whether they were starred

- app/models/concerns/clone/session.rb
- app/models/report_template.rb
- spec/requests/v1/report_templates/update_spec.rb
- [CIAS-3567](https://htdevelopers.atlassian.net/browse/CIAS30-3567)
- when changing the `report_for` field for the report template from `third_party` to `participant` it will remove its id from the answers in the third party question type questions
- cloning a session will now simply omit any invalid ids, also it's optimized not to include an N+1 error
> [CIAS30-3567] Fix report template ids so they are correctly removed when changing the report template type

- app/services/v1/user_session_schedule_service.rb
- spec/services/v1/user_session_schedule_service_spec.rb
- [CIAS-3627](https://htdevelopers.atlassian.net/browse/CIAS30-3627)
- passed missing parameter responsible for status of the user intervention
> [CIAAS30-3627]fix issue with status for some type of scheduling

- app/models/intervention.rb
- spec/requests/v1/interventions/update_spec.rb
- [CIAS-3653](https://htdevelopers.atlassian.net/browse/CIAS30-3653)
- changing the type of sharing for an intervention to `anyone` will now change the scheduling type for all sessions of which their current scheduling mode wouldn't be applicable
> [CIAS30-3653] Fix changing the type of intervention access not updating session scheduling parameters

- app/controllers/v1/interventions/predefined_participants_controller.rb
- app/jobs/data_clear_jobs/clear_user_data.rb
- app/models/ability/predefined_participant.rb
- app/models/intervention.rb
- app/models/predefined_user_parameter.rb
- app/models/user.rb
- app/serializers/v1/predefined_participant_serializer.rb
- app/services/v1/intervention/predefined_participants/create_service.rb
- app/services/v1/intervention/predefined_participants/update_service.rb
- config/routes.rb
- db/migrate/20230901094411_create_predefined_user_parameters.rb
- db/schema.rb
- spec/factories/interventions.rb
- spec/factories/predefined_user_parameters.rb
- spec/factories/users.rb
- spec/jobs/data_clear_jobs/clear_user_data_spec.rb
- spec/models/intervention_spec.rb
- spec/models/predefined_user_parameter_spec.rb
- spec/requests/v1/interventions/predefined_participants/create_spec.rb
- spec/requests/v1/interventions/predefined_participants/index_spec.rb
- spec/requests/v1/interventions/predefined_participants/show_spec.rb
- spec/requests/v1/interventions/predefined_participants/update_spec.rb
- spec/services/v1/intervention/predefined_participants/create_service_spec.rb
- spec/services/v1/intervention/predefined_participants/update_service_spec.rb
- spec/support/shared_examples/predefined_participants/users_without_access.rb
- [CIAS-3636](https://htdevelopers.atlassian.net/browse/CIAS30-3636)
- Predefined participants will now be cleared alongside their `PredefinedUserParameter` when clearing data for an intervention
> [CIAS30-3636] Delete predefined users when clearing intervention data

- app/serializers/v1/user_intervention_serializer.rb
- spec/requests/v1/user_interventions/index_spec.rb
- spec/requests/v1/user_interventions/show_spec.rb
- [CIAS-3671](https://htdevelopers.atlassian.net/browse/CIAS30-3671)
- Fetching a user intervention will now return a body with a field `health_clinic_id` under `attributes`
> [CIAS30-3671] Return health_clinic_id when fetching user intervention

- app/jobs/clone_jobs/intervention.rb
- app/models/concerns/clone.rb
- app/models/concerns/clone/base.rb
- app/models/concerns/clone/intervention.rb
- spec/models/intervention_spec.rb
- [CIAS-3660](https://htdevelopers.atlassian.net/browse/CIAS30-3660)
- Using "Duplicate here" will now clone the intervention and make the user who requested the clone the owner, instead of the owner being always the owner of the original one
> [CIAS30-3660] fix "Duplicate Here" option for invited collaborator making copy to a intervention owner

- app/models/user_intervention.rb
- app/models/user_session.rb
- spec/models/user_intervention_spec.rb
- spec/models/user_session_spec.rb
- [CIAS-3672](https://htdevelopers.atlassian.net/browse/CIAS30-3672)
-
> [CIAS30-3672] Don't allow creating user session without health_clinic_id in interventions inside organization

- app/models/user.rb
- spec/requests/v1/users/invitations/create_spec.rb
- spec/services/v1/users/invitations/create_spec.rb
- [CIAS-3665](https://htdevelopers.atlassian.net/browse/CIAS30-3665)
- `User.invite!` was overridden to check for the correctness of the email address
> [CIAS30-3665] fix the possibility to invite a user with an incorrect email address

- app/services/v1/user_sessions/previous_question_service.rb
- spec/requests/v1/user_sessions/questions/previous_spec.rb
- [CIAS-3689](https://htdevelopers.atlassian.net/browse/CIAS30-3689)
- when using the back button, we mark all answers as draft assigned to this question, instead of the last one
> [CIAS30-3689] mark all answers for the question as draft

- app/models/user_intervention.rb
- app/models/user_session.rb
- spec/models/user_intervention_spec.rb
- spec/models/user_session_spec.rb
- [CIAS-3730](https://htdevelopers.atlassian.net/browse/CIAS30-3730)
- If a user session or a user intervention is inside an organization, but belongs to a preview user the health clinic validation won't be triggered
> [CIAS30-3730] fix researcher cannot open preview when intervention belongs to the organiation

- app/serializers/v1/predefined_participant_serializer.rb
- spec/requests/v1/interventions/predefined_participants/create_spec.rb
- spec/requests/v1/interventions/predefined_participants/index_spec.rb
- spec/requests/v1/interventions/predefined_participants/update_spec.rb
- [CIAS-3733](https://htdevelopers.atlassian.net/browse/CIAS30-3733)
- I have added `active` to predefined_user_serializer
> [CIAS30-3733] add missing attributes to serializer

- app/models/user.rb
- db/schema.rb
- spec/models/user_spec.rb
- [CIAS-3737](https://htdevelopers.atlassian.net/browse/CIAS30-3737)
- detect if a user is a predefined participant and block sending welcome emails to them
> [CIAS30-3737] block sending welcome emails to predefined participants

- app/controllers/v1/user_sessions/answers_controller.rb
- config/locales/en.yml
- spec/requests/v1/answers/create_spec.rb
- [CIAS-3740](https://htdevelopers.atlassian.net/browse/CIAS30-3740)
- EP to create an answer detects if the user session is finished. In this case, the EP will raise an error with a custom msg
> [CIAS30-3740] auto-finish block saving answers

- app/services/v1/intervention/predefined_participants/send_invitation.rb
- config/locales/en.yml
- spec/services/v1/intervention/predefined_participants/send_invitation_spec.rb
- [CIAS-3747](https://htdevelopers.atlassian.net/browse/CIAS30-3747)
- Detect if a user is deactivated and raise the appropriate error
> [CIAS30-3747] block option to send SMSes to deactivated users

- app/controllers/v1/organizations/invitations_controller.rb
- app/controllers/v1_controller.rb
- config/locales/en.yml
- spec/requests/v1/user_sessions/answers/create_spec.rb
- spec/requests/v1/user_sessions/questions/index_spec.rb
- spec/requests/v1/user_sessions/show_spec.rb
- spec/support/shared_examples/deactivated_account.rb
- [CIAS-3745](https://htdevelopers.atlassian.net/browse/CIAS30-3745)
- in the main controller, we detect if a user is activated. Otherwise we raise an error
> [CIAS30-3745] block access to deactivated users

- app/models/concerns/clone/intervention.rb
- app/models/concerns/translate/intervention.rb
- app/models/intervention.rb
- spec/models/intervention_spec.rb
- [CIAS-3759](https://htdevelopers.atlassian.net/browse/CIAS30-3759)
- I have added a logic to duplicate the logo during coping 
- Additionally, translate logo description during translation
> [CIAS30-3759] duplicate and translate intervention's logo

- app/services/concerns/static_link_helper.rb
- spec/requests/v1/interventions/short_links/verify_spec.rb
- [CIAS-3793](https://htdevelopers.atlassian.net/browse/CIAS30-3793)
- I've changed the validation to take into account if user_intervention is completed, before we had a wrong check
> [CIAS30-3793] return session_id when verifying short link of a sequential or fixed-order intervention for the first time as a logged in user

- app/serializers/v1/export/intervention_serializer.rb
- [CIAS-3785](https://htdevelopers.atlassian.net/browse/CIAS30-3785)
- add where to has_many: sessions to skip CatMh sessions during exporting
> [CIAS30-3785] Skip CatMh sessions during exporting

- app/services/v1/sms_plans/schedule_sms_for_user_session.rb
- spec/services/v1/sms_plans/schedule_sms_for_user_session_spec.rb
- [CIAS-3791](https://htdevelopers.atlassian.net/browse/CIAS30-3791)
- When a user had a confirmed phone number and, while filling out, decided to skip answering the question or the session ended on its own an error was thrown. Now in this case the default setting is taken.
> [CIAS30-3791] a participant skips phone screen

- app/services/concerns/static_link_helper.rb
- spec/requests/v1/interventions/short_links/verify_spec.rb
- spec/services/v1/intervention/predefined_participants/verify_service_spec.rb
- [CIAS-3810](https://htdevelopers.atlassian.net/browse/CIAS30-3810)
- set the correct status for `multiple_fill_session_available`
> [CIAS30-3810] incorrect flag when the intervention contains multiple-fill sessions

- app/controllers/v1/twillo_message_controller.rb
- [CIAS-3815](https://htdevelopers.atlassian.net/browse/CIAS30-3815)
- use `transformed_params` instead of `params`
> [CIAS30-3815] fix issue with SMS-STOP-functionality

- app/controllers/v1/interventions/predefined_participants_controller.rb
- app/services/v1/short_links/map_service.rb
- spec/requests/v1/interventions/predefined_participants/verify_spec.rb
- spec/requests/v1/interventions/short_links/verify_spec.rb
- [CIAS-3819](https://htdevelopers.atlassian.net/browse/CIAS30-3819)
- in `predefined_participants/verify` detect case when intervention is draft/paused/closed/archived
- add case with paused intervention to `short_link/verify`
> [CIAS30-3819] Unify errors returned when verifying short links and predefined participants links

- app/services/v1/intervention/predefined_participants/verify_service.rb
- spec/services/v1/intervention/predefined_participants/verify_service_spec.rb
- [CIAS-3839](https://htdevelopers.atlassian.net/browse/CIAS30-3839)
- add missing argument when we fetch or create a user intervention for the predefined participant -> health clinic id
> [CIAS30-3839] User intervention id isn't returned when verifying predefined participant link to reporting intervention

- app/controllers/v1/user_sessions_controller.rb
- config/locales/en.yml
- spec/requests/v1/user_sessions/create_spec.rb
- spec/requests/v1/user_sessions/fetch_or_create_spec.rb
- spec/support/shared_examples/closed_session.rb
- [CIAS-3823](https://htdevelopers.atlassian.net/browse/CIAS30-3823)
- block option to create new user session after close
> [CIAS30-3823] block option to create new user session after close

- app/models/intervention/csv/harvester.rb
- spec/models/intervention/csv/harvester_spec.rb
- [CIAS-3811](https://htdevelopers.atlassian.net/browse/CIAS30-3811)
- in the CSV file, we have the date of the answer to the first question in the started at column instead of the date the session user was created
> [CIAS30-3811] change the place from where we get the "started_at" value in the CSV file 

- app/serializers/v1/user_intervention_serializer.rb
- spec/requests/v1/user_interventions/show_spec.rb
- [CIAS-3891](https://htdevelopers.atlassian.net/browse/CIAS30-3891)
- Detect if a user is the predefined participant and set `blocked` to true
> [CIAS30-3891] set blocked to false if user has assigned predefined participant role

- Gemfile
- Gemfile.lock
- [CIAS30-3980](https://htdevelopers.atlassian.net/browse/CIAS30-3980)
-  new version of heroku stack do not support previous version of wkhtmltopdf
> [CIAS30-3980] Reports are not being sent on new production
