Michigan-State-University/cias-api

.rubocop.yml, app/models/answer/phone.rb, app/models/intervention/csv/harvester.rb, spec/models/intervention/csv/harvester_spec.rb
- [CIAS-3387](https://htdevelopers.atlassian.net/browse/CIAS30-3387)
- modified existing method `csv_row_value` to return additional information (timezone and selected time ranges)
- add tests to cover new parts of the code
=> [CIAS30-3387] add information about selected timezone and preferable time ranges into CSV

app/controllers/v1/audio_controller.rb, app/services/v1/audio/regenerate.rb, config/routes.rb, spec/services/v1/audio/regenerate_spec.rb
- [CIAS-3341](https://htdevelopers.atlassian.net/browse/CIAS30-3341)
- Migrate PR to regenerate audia
=> [CIAS-3341] -  Regenerate audio

db/migrate/20230605101854_update_settings_in_exisiting_number_questions.rb, db/schema.rb
- [CIAS-3402](https://htdevelopers.atlassian.net/browse/CIAS30-3402)
- add a new migration to add new values to settings in number questions
=> [CIAS30-3402] add new values to settings in number questions - max and min length 

lib/tasks/fetch_researchers.rake
- [CIAS30-3421](https://htdevelopers.atlassian.net/browse/CIAS30-3421)
- rake task to fetch researchers and print in terminal
=> [CIAS30-3421] script to fetch researchers

app/models/intervention.rb, app/services/v1/intervention/collaborators/create_service.rb, spec/services/v1/intervention/collaborators/create_service_spec.rb
- [CIAS-3446](https://htdevelopers.atlassian.net/browse/CIAS30-3446)
- allow adding a super admin to collaborators
- modified a little bit the test also to check new case
=> [CIAS30-3446] allow adding a super admin to collaborators

app/controllers/v1/interventions_controller.rb, app/serializers/v1/simple_intervention_serializer.rb
- [CIAS-3419](https://htdevelopers.atlassian.net/browse/CIAS30-3419)
- Add simple intervention serializer
=> [CIAS-3419] - Add simple intervention serializer

app/serializers/v1/intervention_serializer.rb, app/serializers/v1/simple_intervention_serializer.rb
- [CIAS-3419](https://htdevelopers.atlassian.net/browse/CIAS30-3419)
- Fix cache and add missing field to serializer
=> [CIAS-3419] - Fix cache key

db/migrate/20230629094119_clear_cache.rb, db/schema.rb, lib/tasks/clear_cache.rake
- [CIAS-3469](https://htdevelopers.atlassian.net/browse/CIAS30-3469)
- rake to clear cache
=> [CIAS30-3469] task witch clear cache during the next deploy

.env.template, .rubocop.yml, Gemfile, app/services/api/epic_on_fhir/appointments.rb, app/services/api/epic_on_fhir/base_service.rb, app/services/api/epic_on_fhir/patient_verification.rb, app/services/v1/henry_ford/verify_service.rb, config/locales/en.yml, spec/services/api/epic_on_fhir/appointments_spec.rb
- [CIAS-3373](https://htdevelopers.atlassian.net/browse/CIAS30-3373)
-
=> [CIAS30-3373] fetch appointments from epic

README.md
Slight modifications to description of features and access model. Identical to changes made on cias-web.
-
=> Update README.md by Steve

.github/ISSUE_TEMPLATE/bug_report.md, CONTRIBUTING.md, README.md
- [CIAS-3486](https://htdevelopers.atlassian.net/browse/CIAS30-3486)
- as title
=> [CIAS30-3486] Update repo links in documentation

app/models/question/henry_ford_initial.rb, spec/models/intervention/csv/harvester_spec.rb
- [CIAS-3483](https://htdevelopers.atlassian.net/browse/CIAS30-3483)
- added missing columns to the CVS 
-  phone number
- phone type
=> [CIAS30-3483] add new columns to our CSV

.env.template, app/controllers/v1/henry_ford/patient_details_controller.rb, config/initializers/cors.rb
- [CIAS-3374](https://htdevelopers.atlassian.net/browse/CIAS30-3374)
- we don't need some part of the code after changing the flow
=> [CIAS30-3374]removed unneeded part of the code

Gemfile, Gemfile.lock, app/models/intervention/csv/harvester.rb, spec/models/intervention/csv/harvester_spec.rb
- [CIAS-3417](https://htdevelopers.atlassian.net/browse/CIAS30-3417)
- fix for beloved edge case:
- when the researcher has changed the settings from off to on for `multiple_fill` and trigger generation of CSV our system got `nil` in an unexpected place
=> [CIAS30-3417] fix for error while generating CSV

app/models/concerns/clone.rb, app/services/v1/question_group/share_externally_service.rb, db/schema.rb, spec/models/intervention_spec.rb, spec/services/v1/question_group/share_externally_service_spec.rb
- [CIAS-3492](https://htdevelopers.atlassian.net/browse/CIAS30-3492)
- use #downcase to successfully search users by email
=> [CIAS30-3492] "Share Externally" modal is not case sensitive

config/locales/en.yml
=> DEV => TEST 18/07/23

app/jobs/clone_jobs/intervention.rb, app/jobs/clone_jobs/session.rb, app/mailers/clone_mailer.rb, app/models/chart.rb, app/models/concerns/clone.rb, app/models/concerns/clone/chart.rb, app/models/concerns/clone/session.rb, app/serializers/v1/user_session_serializer.rb, app/services/v1/charts/create.rb, app/services/v1/flow_service/next_question/branching_service.rb, app/services/v1/question_group/share_externally_service.rb, app/services/v1/user_sessions/base_service.rb, app/services/v1/user_sessions/fetch_service.rb, app/views/clone_mailer/cloned_intervention_activate.html.erb, app/views/clone_mailer/cloned_question_group_activate.erb, app/views/intervention_mailer/share_externally_and_registration.html.erb, app/views/intervention_mailer/share_question_group_and_registration.html.erb, config/locales/en.yml, db/migrate/20230720080937_add_started_flag_to_user_sessions.rb, db/schema.rb, spec/jobs/clone_jobs/intervention_spec.rb, spec/jobs/clone_jobs/session_spec.rb, spec/jobs/duplicate_jobs/session_spec.rb, spec/requests/v1/charts/clone_spec.rb, spec/requests/v1/charts/create_spec.rb, spec/requests/v1/user_sessions/fetch_or_create_spec.rb, spec/requests/v1/user_sessions/show_spec.rb, spec/services/v1/question_group/share_externally_service_spec.rb, spec/services/v1/user_sessions/create_service_spec.rb, spec/support/shared_examples/create_user_session.rb
=> DEV => TEST 27/07/2023

app/services/v1/flow_service/schedule_service.rb
=> DEV => TEST 27/07/2023 v2

app/views/clone_mailer/cloned_intervention_activate.html.erb
- [CIAS-3549](https://htdevelopers.atlassian.net/browse/CIAS30-3549)
- the wrong env used to generate a link in an email
=> HOT FIX -> bug with invitation emails 

app/views/clone_mailer/cloned_intervention_activate.html.erb, app/views/clone_mailer/cloned_question_group_activate.erb
=> Test to Master 02/08/2023

app/models/concerns/clone/report_template.rb, app/models/concerns/clone/session.rb, app/serializers/v1/report_template_serializer.rb, db/migrate/20230808084201_rename_is_duplicated_in_report_template.rb, db/schema.rb, spec/models/report_template_spec.rb
- [CIAS-](https://htdevelopers.atlassian.net/browse/CIAS30-3563)
- renamed the column from 'isDuplicated' to 'isDuplicatedFromOtherSession' 
- added option to control this flag
=> [Cias30-3563] rename flag

app/controllers/v1/sessions/report_templates_controller.rb, app/models/concerns/clone/report_template.rb, app/models/concerns/clone/session.rb, app/serializers/v1/report_template_serializer.rb, config/routes.rb, db/migrate/20230808084201_rename_is_duplicated_in_report_template.rb, db/schema.rb, spec/models/report_template_spec.rb, spec/requests/v1/report_templates/duplicate_spec.rb
- [CIAS-3407](https://htdevelopers.atlassian.net/browse/CIAS30-3407)
- New endpoint to duplicate the report template in any session in the intervention
=> [CIAS30-3407] endpoint to duplicate report

app/models/session/classic.rb, spec/requests/v1/sessions/fetch_variables_spec.rb
- [CIAS-475](https://htdevelopers.atlassian.net/browse/CIAS30-3475)
- to allow new question types to be used in formulas, they should be added to the filter
=> [CIAS30-3475] add questions to the filter

app/controllers/concerns/resource/reorder.rb, app/controllers/v1/report_templates/sections/variants_controller.rb, app/controllers/v1/report_templates/sections_controller.rb, app/controllers/v1/sms_plans/variants_controller.rb, app/models/report_template/section/variant.rb, app/serializers/v1/report_template/section/variant_serializer.rb, config/routes.rb, db/migrate/20230807064042_add_position_to_report_template_section_variants.rb, db/migrate/20230807075218_set_correct_possition_of_variants.rb, db/schema.rb, lib/tasks/one_time_use/assign_correct_position_to_report_template_variants.rake, spec/requests/v1/report_templates/sections/move_spec.rb, spec/requests/v1/report_templates/sections/variants/move_spec.rb, spec/requests/v1/sms_plans/variants/move_spec.rb, spec/support/shared_examples/with_collaborators.rb
- [CIAS-3445](https://htdevelopers.atlassian.net/browse/CIAS30-3445)
- new endpoint to re-order variant in report templates
=> [CIAS30-3445] a new endpoint to reorder

app/models/intervention.rb, spec/requests/v1/interventions/index_spec.rb
- [CIAS-3558](https://htdevelopers.atlassian.net/browse/CIAS30-3558)
- The filter was adjusted to better more intuitive
=> [CIAS30-3558] the filter was adjusted to better meet customer expectations

app/controllers/v1/interventions_controller.rb, app/jobs/data_clear_jobs/inform_and_schedule.rb, app/mailers/intervention_mailer/clear_data_mailer.rb, app/views/intervention_mailer/clear_data_mailer/inform.html.erb, config/locales/en.yml, spec/jobs/data_clear_jobs/inform_and_schedule_spec.rb, spec/requests/v1/interventions/clear_user_data_spec.rb
- [CIAS-3578](https://htdevelopers.atlassian.net/browse/CIAS30-3578)
- job to send an email with information that the reports will be deleted
=> [CIAS30-3578] job to send an email with information that the reports will be deleted

app/controllers/v1/interventions_controller.rb, app/jobs/data_clear_jobs/clear_user_data.rb, app/jobs/data_clear_jobs/inform_and_schedule.rb, app/mailers/intervention_mailer/clear_data_mailer.rb, app/models/notification.rb, app/views/intervention_mailer/clear_data_mailer/inform.html.erb, config/locales/en.yml, spec/jobs/data_clear_jobs/clear_user_data_spec.rb, spec/jobs/data_clear_jobs/inform_and_schedule_spec.rb, spec/requests/v1/interventions/clear_user_data_spec.rb
- [CIAS-3580](https://htdevelopers.atlassian.net/browse/CIAS30-3580)
- create notification after clear the data
=> [CIAS30-3580] create notification after clear the data

Gemfile, Gemfile.lock, app/models/concerns/clone/report_template.rb, app/models/report_template/section/variant.rb, spec/models/report_template_spec.rb, spec/requests/v1/report_templates/sections/variants/create_spec.rb
- [CIAS-3583](https://htdevelopers.atlassian.net/browse/CIAS30-3583)
- new method to generate a unique name for the report template
- assign the next position to variants in a report template
=> [CIAS30-3583] Bug fixing of report templates

Gemfile, Gemfile.lock, app/models/concerns/clone/report_template.rb, app/models/report_template/section/variant.rb, spec/models/report_template_spec.rb, spec/requests/v1/report_templates/sections/variants/create_spec.rb
=> DEV ==> TEST [21-08-2023]

app/services/api/documo/send_multiple_faxes.rb
- [CIAS-3526](https://htdevelopers.atlassian.net/browse/CIAS30-3526)
- new method which generates a hash with all custom fields
=> [Cias30-3526] add custom fields to request

app/controllers/v1/organizations/charts_data/charts_data_controller.rb, app/services/v1/chart_statistics/bar_chart.rb, spec/requests/v1/charts/update_spec.rb, spec/requests/v1/henry_ford/patient_details/verify_spec.rb, spec/services/v1/chart_statistics/bar_chart/numeric_spec.rb, spec/services/v1/chart_statistics/bar_chart/percentage_spec.rb
- [CIAS-3607](https://htdevelopers.atlassian.net/browse/CIAS30-3607)
- Add an option to generate a label based on the chart's interval type 
- modify way to move to the next period (base on the chart's interval type )
=> [CIAS30-3607] generate quarterly charts

app/services/v1/chart_statistics/base.rb
- [CIAS-3134](https://htdevelopers.atlassian.net/browse/CIAS30-3134)
-
=> [CIAS30-3134] load all the count values as a hash so you only need one call to the DB

app/serializers/v1/live_chat/interventions/live_chat_setup_serializer.rb, app/serializers/v1/user_intervention_serializer.rb, app/serializers/v1/user_session_serializer.rb, spec/requests/v1/user_interventions/index_spec.rb, spec/requests/v1/user_interventions/show_spec.rb, spec/requests/v1/user_sessions/show_spec.rb
- [CIAS-3593](https://htdevelopers.atlassian.net/browse/CIAS30-3593)
- adjustments requested by FE
=> change place when information about navigators is

db/seeds/interventions/chart_data_seed.rb, lib/tasks/create_mock_chart_data.rake
- [CIAS-3626](https://htdevelopers.atlassian.net/browse/CIAS30-3626)
- a new rake task to create mock data over a long period of time for testing charts
=> [CIAS30-3626] add the rake task to seed the database with correct data

app/services/v1/chart_statistics/create.rb, spec/services/v1/chart_statistics/create_spec.rb
- [CIAS-3608](https://htdevelopers.atlassian.net/browse/CIAS30-3608)
- Pie charts now support time ranges defined by `date_range_start` and `date_range_end`, which are used for filtering
=> [CIAS30-3608] Take new parameters into consideration when calculating data for pie charts

app/models/ability/predefined_participant.rb, app/models/predefined_user_parameter.rb, app/models/user.rb, db/migrate/20230901094411_create_predefined_user_parameters.rb, db/schema.rb, spec/models/predefined_user_parameter_spec.rb
- [CIAS-3633](https://htdevelopers.atlassian.net/browse/CIAS30-3633)
- added new ability and type of user
- added new table to containing all additional parameters for predefined user
=> [CIAS30-3633] add predefined user

.rubocop.yml, app/jobs/data_clear_jobs/clear_user_data.rb, app/jobs/session_schedule_job.rb, app/jobs/sms_plans/send_sms_job.rb, app/models/user_session/classic.rb, app/services/v1/sms_plans/cancel_scheduled_smses.rb, app/services/v1/sms_plans/schedule_sms_for_user_session.rb, spec/factories/user_sessions.rb, spec/jobs/session_schedule_job_spec.rb, spec/models/user_session_spec.rb, spec/services/v1/sms_plans/cancel_scheduled_smses_spec.rb, spec/services/v1/sms_plans/schedule_sms_for_user_session_spec.rb, spec/spec_helper.rb
- [CIAS-3625](https://htdevelopers.atlassian.net/browse/CIAS30-3625)
- terminate the scheduled jobs when intervention data has been cleared
- SmsJob
- AutoFinishJob
=> [CIAS30-3625] terminate the scheduled jobs when intervention data has been cleared

app/controllers/v1/interventions/predefined_participants_controller.rb, app/models/ability/predefined_participant.rb, app/models/intervention.rb, app/models/predefined_user_parameter.rb, app/models/user.rb, app/serializers/v1/predefined_participant_serializer.rb, app/services/v1/intervention/predefined_participants/create_service.rb, app/services/v1/intervention/predefined_participants/update_service.rb, config/routes.rb, db/migrate/20230901094411_create_predefined_user_parameters.rb, db/schema.rb, spec/factories/interventions.rb, spec/factories/predefined_user_parameters.rb, spec/factories/users.rb, spec/models/intervention_spec.rb, spec/models/predefined_user_parameter_spec.rb, spec/requests/v1/interventions/predefined_participants/create_spec.rb, spec/requests/v1/interventions/predefined_participants/index_spec.rb, spec/requests/v1/interventions/predefined_participants/show_spec.rb, spec/requests/v1/interventions/predefined_participants/update_spec.rb, spec/services/v1/intervention/predefined_participants/create_service_spec.rb, spec/services/v1/intervention/predefined_participants/update_service_spec.rb, spec/support/shared_examples/predefined_participants/users_without_access.rb
- [CIAS-3637](https://htdevelopers.atlassian.net/browse/CIAS30-3637)
-
=> [CIAS30-3637] CRUD for predefined users

app/services/v1/sms_plans/schedule_sms_for_user_session.rb, spec/services/v1/sms_plans/schedule_sms_for_user_session_spec.rb
- [CIAS-3675](https://htdevelopers.atlassian.net/browse/CIAS30-3675)
- I have divided sending SMSes into two parts: 
- sending alerts no mater what 
- sending normal SMSes after checking settings and phone
=> [CIAS30-3675] send alerts no matter what 

app/controllers/v1/interventions/predefined_participants_controller.rb, app/models/ability/predefined_participant.rb, app/services/v1/intervention/predefined_participants/verify_service.rb, spec/requests/v1/interventions/predefined_participants/verify_spec.rb, spec/services/v1/intervention/predefined_participants/verify_service_spec.rb
- [CIAS-3704](https://htdevelopers.atlassian.net/browse/CIAS30-3704)
- check if the intervention is completed
- check if other then predefined participant try to verify slug
=> [CIAS30-3704] 'verify' sometimes return 500

app/models/concerns/clone/intervention.rb, spec/models/intervention_spec.rb
- [CIAS-3714](https://htdevelopers.atlassian.net/browse/CIAS30-3714)
-  resetting counters during copy intervention
=> [CIAS30-3714] reset cache counters for the outcome

app/jobs/data_clear_jobs/inform_and_schedule.rb, app/mailers/intervention_mailer/clear_data_mailer.rb, spec/jobs/data_clear_jobs/inform_and_schedule_spec.rb
- [CIAS-3715](https://htdevelopers.atlassian.net/browse/CIAS30-3715)
- The number of days left until the data will be deleted now shows the correct value
=> [CIAS30-3715] Fix the email sent to participants not showing the correct number of days

app/services/v1/answer_service.rb, db/migrate/20230926081202_add_uniq_index_to_answers.rb, db/schema.rb, spec/services/v1/intervention/publish_spec.rb
- [CIAS-3713](https://htdevelopers.atlassian.net/browse/CIAS30-3713)
- unique index with conditions for answers
=> [CIAS30-3713] Partial uniq index for answer

app/controllers/v1/interventions/predefined_participants_controller.rb, app/models/intervention/csv/harvester.rb, app/models/user.rb, app/serializers/v1/predefined_participant_serializer.rb, app/services/v1/intervention/predefined_participants/create_service.rb, app/services/v1/intervention/predefined_participants/update_service.rb, db/migrate/20230927095211_add_external_id_to_predefined_users.rb, db/schema.rb, spec/models/intervention/csv/harvester_spec.rb, spec/requests/v1/interventions/predefined_participants/create_spec.rb, spec/requests/v1/interventions/predefined_participants/index_spec.rb, spec/requests/v1/interventions/predefined_participants/update_spec.rb
- [CIAS-3728](https://htdevelopers.atlassian.net/browse/CIAS30-3728)
- [CIAS-3729](https://htdevelopers.atlassian.net/browse/CIAS30-3729)
- I have added one additional field: 
- external id 
-  add to CSV file information about predefined user
=> [CIAS30-3728][CIAS-3729] small changes related to predefined users 

app/models/intervention/csv/harvester.rb, spec/models/intervention/csv/harvester_spec.rb, spec/requests/v1/user_sessions/questions/previous_spec.rb
- [CIAS-3731](https://htdevelopers.atlassian.net/browse/CIAS30-3731)
- CSV rows completion relative to the first fill (session creation date)
=> [CIAS30-3731] add order by after group_by

app/models/user_session.rb, app/services/v1/user_sessions/base_service.rb, db/migrate/20230929101211_add_partial_index_on_user_intervention.rb, db/migrate/20230929103257_add_information_about_multiple_session.rb, db/schema.rb, spec/factories/user_sessions.rb, spec/models/user_intervention_spec.rb, spec/models/user_session_spec.rb, spec/requests/v1/user_interventions/index_spec.rb, spec/requests/v1/user_sessions/questions/index_spec.rb, spec/services/v1/user_session_schedule_service_spec.rb
- [CIAS-3677](https://htdevelopers.atlassian.net/browse/CIAS30-3677)
- When trying to create a user session with the same user and session associated, the callback in the user session model will raise an error
- It does not apply to multiple fill session
=> [CIAS30-3677] Add validation to the user session controller to check if a session can have multiple user_sessions for the same participant

app/services/v1/intervention/predefined_participants/update_service.rb, db/schema.rb, spec/services/v1/intervention/predefined_participants/update_service_spec.rb
- [CIAS-3735](https://htdevelopers.atlassian.net/browse/CIAS30-3735)
- I have added logic to detect if `phone_attribiutes` is blank and remove the assigned phone number (if exists)
=> [CIAS30-3735] fix for "phone number is not being cleared"

app/services/v1/henry_ford/verify_service.rb
- [CIAS-3143](https://htdevelopers.atlassian.net/browse/CIAS30-3143)
-
=> Restore possibility to search by MRN 

app/services/v1/intervention/predefined_participants/update_service.rb
- [CIAS-3751](https://htdevelopers.atlassian.net/browse/CIAS30-3751)
- return up-to-data information after update
=> [CIAS30-3751] return up-to-data information after update 

app/services/v1/henry_ford/verify_service.rb
- [CIAS-3735](https://htdevelopers.atlassian.net/browse/CIAS30-3735)
- allow for appointments from the past base on ENV's variable
=> [CIAS30-3735] allow for appointments from the past 

app/services/v1/intervention/predefined_participants/update_service.rb
- [CIAS-3751](https://htdevelopers.atlassian.net/browse/CIAS30-3751)
- update a user to make sure that everything is up-to-date
=> [CIAS30-3751] phone number is present after delete

README.md
- [CIAS-3758](https://htdevelopers.atlassian.net/browse/CIAS30-3758)
- as title
=> [CIAS30-3758] Add link to frontend repository in readme

app/models/concerns/translate/report_template.rb, app/models/report_template.rb, spec/models/report_template_spec.rb
- [CIAS-3761](https://htdevelopers.atlassian.net/browse/CIAS30-3761)
- translate fax attributes: 
-  cover_letter_sender
- cover_letter_description
=> [CIAS30-3761] translate fax attributes

app/models/clinic_location.rb, app/services/v1/henry_ford/verify_service.rb, db/migrate/20231018071455_add_external_name_to_clinic_location.rb, db/schema.rb, lib/tasks/one_time_use/add_external_name_to_clinic_locations.rake, spec/requests/v1/henry_ford/patient_details/verify_spec.rb, spec/services/v1/henry_ford/verify_service_spec.rb
- [CIAS-3757](https://htdevelopers.atlassian.net/browse/CIAS30-3757)
- I have added an external name to clinic locations and I have changed the validation
=> [CIAS30-3757]add external name to clinic locations

config/locales/en.yml
- [CIAS-3768](https://htdevelopers.atlassian.net/browse/CIAS30-3768)
- a new copy in an SMS message sent to previously defined participants
=> [CIAS30-3768] a new copy in an SMS message sent to previously defined participants

app/views/report_templates/report_preview.html.erb
- [CIAS-3695](https://htdevelopers.atlassian.net/browse/CIAS30-3695)
Before
After
=> [CIAS30-3695] Handle RTL text in PDF reports

app/serializers/v1/intervention_serializer.rb, spec/requests/v1/interventions/logos/create_spec.rb, spec/requests/v1/interventions/logos/update_spec.rb, spec/requests/v1/interventions/show_spec.rb
- [CIAS-3796](https://htdevelopers.atlassian.net/browse/CIAS30-3796)
- information about files like date of generation, URL are wraped in the super key
=> [CIAS30-3796] new structure of returned data

config/locales/en.yml, spec/requests/v1/interventions/short_links/verify_spec.rb
- [CIAS-3787](https://htdevelopers.atlassian.net/browse/CIAS30-3787)
- changing the copy to the text provided by the client
=> [CIAS30-3787] change of copy for predefined participants

app/services/v1/henry_ford/verify_service.rb, spec/requests/v1/interventions/short_links/verify_spec.rb
=> Test into dev 07 11 2023

db/schema.rb
- [CIAS-3803](https://htdevelopers.atlassian.net/browse/CIAS30-3803)
- ability to update logo description
=> [CIAS30-3803] ability to update logo description

app/serializers/v1/intervention_serializer.rb, app/serializers/v1/simple_intervention_serializer.rb, config/locales/en.yml, db/migrate/20231114061351_clear_cache_for_simple_interventions_serializer.rb, db/schema.rb
- I've added the exported data field to simple_intervention_serializer;
- I've added the filename to the exported data key
- I've changed a little bit of copy to fit better to the current implementation in the email sent to the researcher when the file is ready to download
=> [CIAS30-3808] small improvements

app/controllers/v1/user_interventions_controller.rb, app/serializers/v1/user_intervention_serializer.rb, db/schema.rb, spec/requests/v1/user_interventions/index_spec.rb, spec/requests/v1/user_interventions/show_spec.rb
- [CIAS-3801](https://htdevelopers.atlassian.net/browse/CIAS30-3801)
- return paused user_intervention
=> [CIAS0-3801] return paused user_intervention

app/controllers/v1/twillo_message_controller.rb, app/controllers/v1/user_interventions_controller.rb, app/services/v1/user_sessions/create_service.rb, spec/services/v1/user_sessions/create_service_spec.rb
- [CIAS-3813](https://htdevelopers.atlassian.net/browse/CIAS30-3813)
- set user language during create user_session
=> [CIAS30-3813] send SMS in different language

app/serializers/v1/user_intervention_serializer.rb, spec/requests/v1/user_interventions/index_spec.rb
- [CIAS-3840](https://htdevelopers.atlassian.net/browse/CIAS30-3840)
- ignore the size of characters to define if user intervention is blocked or not
=> [CIAS30-3840] hot fix with intervention_accesses

app/controllers/v1/interventions/logos_controller.rb
- [CIAS-3842](https://htdevelopers.atlassian.net/browse/CIAS30-3842)
- call `.touch` to remove intervention from cached responses
=> [CIAS30-3842] issue with alt text in the logo

app/controllers/v1/sessions_controller.rb, app/models/session.rb, app/serializers/v1/session_serializer.rb, db/migrate/20230926081202_add_uniq_index_to_answers.rb, db/migrate/20230929101211_add_partial_index_on_user_intervention.rb, db/migrate/20230929103257_add_information_about_multiple_session.rb, db/migrate/20231129073515_add_information_about_autoclosed_the_session.rb, db/schema.rb, spec/requests/v1/sessions/show_spec.rb
- [CIAS30-3828](https://htdevelopers.atlassian.net/browse/CIAS30-3828)
- two new columns in sessions_table
=> [CIAS30-3828] add column responsible for auto closing

app/models/hfhs_patient_detail.rb, app/serializers/v1/hfhs_patient_detail_serializer.rb, app/services/v1/henry_ford/verify_service.rb, db/migrate/20231211092832_set_columns_in_hfhs_patient_details_as_optional.rb, db/schema.rb, spec/factories/users.rb, spec/requests/v1/user_sessions/questions/previous_spec.rb, spec/services/v1/henry_ford/verify_service_spec.rb
- [CIAS-3850](https://htdevelopers.atlassian.net/browse/CIAS30-3850)
- Handle optional HF initial screen fields
=> [CIAS30-3850] Handle optional HF initial screen fields

app/services/v1/flow_service/next_question.rb
- [CIAS-3847](https://htdevelopers.atlassian.net/browse/CIAS30-3847)
- I've added the missing method
=> [CIAS30-3847] Participant cannot access finish screen when next sessions is scheduled based on provided date

.github/workflows/ci.yml, app/models/intervention.rb, spec/requests/v1/interventions/access/create_spec.rb
- [CIAS-3866](https://htdevelopers.atlassian.net/browse/CIAS30-3866)
- changing the supplied emails to lowercase
=> [CIAS30-3866] In the InterventionAccess, emails are case-sensitive

.github/workflows/ci.yml, app/controllers/v1/user_sessions_controller.rb, app/services/v1/user_session_schedule_service.rb
- [CIAS-3881](https://htdevelopers.atlassian.net/browse/CIAS30-3881)
- finish session when autoclose_at is from past
=> [CIAS30-3881]

app/services/v1/flow_service/reflection_service.rb, app/services/v1/user_sessions/previous_question_service.rb, spec/requests/v1/user_sessions/questions/previous_spec.rb
- [CIAS-3877](https://htdevelopers.atlassian.net/browse/CIAS30-3877)
-
=> CIAS30-3877 Use reflection service while fetching previous question

Gemfile, Gemfile.lock, app/services/v1/question/update.rb, config/locales/en.yml, spec/requests/v1/questions/update_spec.rb
- [CIAS-3867](https://htdevelopers.atlassian.net/browse/CIAS30-3867)
- I've added validation to detect if in the session the same variable already exists (ignore letter size)
=> [CIAS30-3867] Variables should be case-insensitive

Gemfile, Gemfile.lock, app/controllers/v1/user_sessions_controller.rb, app/models/ability/admin.rb, app/models/ability/researcher.rb, app/models/ability/team_admin.rb, spec/abilities/user_sessions_spec.rb, spec/factories/sessions.rb, spec/requests/v1/user_sessions/create_spec.rb, spec/requests/v1/user_sessions/fetch_or_create_spec.rb, spec/support/shared_examples/create_user_session.rb
- [CIAS-3887](https://htdevelopers.atlassian.net/browse/CIAS30-3887)
- Admin/Researcher shouldn't be able to fill the session
=> [CIAS30-3887] Block researchers from filling sessions

Gemfile, Gemfile.lock, config/locales/en.yml, spec/support/shared_examples/paused_intervention.rb
- [CIAS-3889](https://htdevelopers.atlassian.net/browse/CIAS30-3889)
- I've replaced the copy in the dictionary
=> [CIAS30-3889] Update error message when participant interacts with paused intervention

Gemfile, Gemfile.lock, app/services/v1/henry_ford/verify_service.rb
- [CIAS-3903](https://htdevelopers.atlassian.net/browse/CIAS30-3903)
- I added a check to see if the date is uploaded before trying to parse it
=> [CIAS30-3903] unexpected error on HFHS::InitialScreen

Gemfile, Gemfile.lock, app/models/ability/admin.rb, app/models/ability/researcher.rb, app/models/ability/team_admin.rb, app/models/session.rb, app/models/session/cat_mh.rb, app/models/session/classic.rb, app/services/v1/question/update.rb, config/locales/en.yml, spec/abilities/user_sessions_spec.rb, spec/factories/sessions.rb, spec/requests/v1/questions/update_spec.rb, spec/requests/v1/user_sessions/create_spec.rb, spec/requests/v1/user_sessions/fetch_or_create_spec.rb, spec/support/shared_examples/create_user_session.rb, spec/support/shared_examples/paused_intervention.rb
=> DEV ==> TEST [18.01.2024]

Gemfile, Gemfile.lock, app/models/question/finish.rb, config/application.rb, config/locales/es.yml
- [CIAS-3875](https://htdevelopers.atlassian.net/browse/CIAS30-3875)
- new Spanish translations for emails/SMSes
=> [CIAS30-3875] spanish translation

app/services/v1/henry_ford/verify_service.rb, db/migrate/20240312120947_add_columns_to_clinic_location_for_epic_identifiers.rb, db/migrate/20240312121037_update_clinic_location_names_from_henry_ford.rb, db/schema.rb
* CIAS30-Fix-HFHS-integration-problems Update names in ClinicLocations, add fields to store HFHS identifier
* CIAS30-Fix-HFHS-integration-problems Add migration adding new columns to ClinicLocation
* CIAS30-Fix-HFHS-integration-problems Remove redundant byebug
=> DEV => TEST 12.03.2024

app/models/ability/generic/sms_plan_access.rb
- [CIAS30-3308](https://htdevelopers.atlassian.net/browse/CIAS30-3308)
-
=> [CIAS30-3308] Add ability to manage SmsLinks by researchers

db/migrate/20240528131542_modify_unique_answers_index.rb, db/migrate/20240702133928_add_missing_uniq_index_to_answers.rb, db/schema.rb
=> HOTFIX: added missing uniq answers index

db/migrate/20240702133928_add_missing_uniq_index_to_answers.rb, db/schema.rb
=> Hotfix prepared alternative version of index

db/migrate/20240702133928_add_missing_uniq_index_to_answers.rb, db/schema.rb
=> Technical branch

app/services/v1/sms/replay.rb, config/locales/en.yml, spec/requests/v1/twillo_message/create_spec.rb
=> SMS_CAMPAIGNS: fixed badly working replay service

app/jobs/after_finish_user_session_job.rb, app/jobs/hfhs/send_answers_job.rb, app/services/api/epic_on_fhir/appointments.rb, config/sidekiq.yml, spec/services/api/epic_on_fhir/appointments_spec.rb
- Added new queues to finish session job and job sending data to hfhs due to possible delays in sending data
- Added missing param to appointments endpoint
=> CIAS30 HFHS errors

app/controllers/v1/sessions_controller.rb, app/models/intervention.rb, app/models/session.rb, app/serializers/v1/export/session_serializer.rb, app/serializers/v1/session_serializer.rb, app/serializers/v1/user_session_serializer.rb, db/migrate/20240801065512_add_google_language_to_sessions.rb, db/schema.rb, spec/performance/sessions_spec.rb
=> TRANSLATION_ISSUE-add-session-based-language

app/serializers/v1/question_serializer.rb
=> TRANSLATIN_ISSUE_FIX: added session language to question serializer

app/serializers/v1/question_serializer.rb, spec/requests/v1/external_links/show_website_metadata_spec.rb
=> dev -> test 16.08

app/controllers/v1/organizations/charts_data/charts_data_controller.rb, app/models/chart.rb, app/services/v1/chart_statistics/bar_chart.rb, app/services/v1/chart_statistics/create_for_user_sessions.rb, app/services/v1/chart_statistics/generate_statistics.rb, app/services/v1/chart_statistics/pie_chart.rb, spec/requests/v1/external_links/show_website_metadata_spec.rb
=> Dashboard issue enhance dashboards performance

app/jobs/user_session_jobs/schedule_daily_messages_job.rb, app/services/v1/sms/replay.rb
=> CIAS30-3936-Ability-to-send-SMS-information-messages-on-the-same-day-with-SMS-questions

Gemfile.lock
=> REXML-UPDATE: updated gemfile.lock

Gemfile.lock, app/models/concerns/clone/report_template.rb
- [CIAS30-3932](https://htdevelopers.atlassian.net/browse/CIAS30-3932)
-
=> [CIAS30-3932] Copy images while copying raport templates

app/services/v1/generated_reports/create.rb, spec/services/v1/generated_reports/create_spec.rb
=> CIAS30-3929: added conditional section rendering

app/models/concerns/clone/report_template.rb
- [CIAS30-3932](https://htdevelopers.atlassian.net/browse/CIAS30-3932 )
-
=> CIAS30-3932 Copy images from all cases while copying report templates

app/controllers/v1/user_interventions_controller.rb, app/models/ability/generic/fill_intervention_access.rb, app/models/intervention/flexible_order.rb, spec/models/intervention/flexible_order_spec.rb, spec/requests/v1/user_interventions/create_spec.rb
=> CIAS30-3939: added ability to share flexible modular intervention to anyone with the link

app/views/report_templates/report_preview.html.erb
- [CIAS30-3940](https://htdevelopers.atlassian.net/browse/CIAS30-3940)
-
=> [CIAS30-3940] Handle rich text in reports

app/controllers/v1/sms_plans_controller.rb, app/models/sms_plan.rb, app/serializers/v1/export/sms_plan_serializer.rb, app/serializers/v1/sms_plan_serializer.rb, app/services/v1/sms_plans/schedule_sms_for_user_session.rb, db/migrate/20240919104701_add_schedule_variable_to_sms_plan.rb, db/schema.rb
=> CIAS30-3941: ability to send sms after user defined time

config/cable.yml, config/initializers/active_job_adapter.rb
=> SIDEKIQ_UPDATE: updated sidekiq config

app/jobs/send_fill_invitation/session_job.rb, app/models/session.rb, app/services/v1/session_or_intervention/link.rb, config/locales/en.yml, spec/jobs/send_fill_invitation/session_job_spec.rb, spec/services/v1/session_or_intervention/link_spec.rb
=> CIAS30-3939: added ability to send invitations to anyone with the link

config/cable.yml, config/initializers/active_job_adapter.rb
=> SIDEKIQ_UPDATE: updated sidekiq config with conditional config

app/jobs/send_fill_invitation/intervention_job.rb, app/models/intervention.rb, spec/jobs/send_fill_invitation/intervention_job_spec.rb
=> EMAIL_INVITATIONS: fixes for modular inerventions

app/controllers/v1/user_sessions/answers_controller.rb, app/models/answer.rb, app/models/intervention/csv/harvester.rb, app/models/session/classic.rb, db/migrate/20241004130904_add_video_stats_to_answers.rb, db/schema.rb
=> VIDEO_TRACKING: ability to track video statistics

app/models/answer.rb, app/models/intervention/csv/harvester.rb
=> VIDEO_TRACKING_ENHANCEMENTS: divided video_stats into separate columns in csv report

Gemfile.lock, app/models/google_language.rb
=> FIXES_FOR_DEFAULT_GOOGLE_VOICES: added proper support for default google voice

app/jobs/user_session_jobs/schedule_daily_messages_job.rb, app/jobs/user_session_jobs/send_question_sms_job.rb, app/services/v1/sms/replay.rb, spec/jobs/user_session_jobs/send_question_sms_job_spec.rb
=> SMS_FIXES: all necessary fixes

Gemfile, Gemfile.lock
=> GEM_UPDATE: updated rails_html_sanitizer

app/models/google_language.rb
- [CIAS30-3948](https://htdevelopers.atlassian.net/browse/CIAS30-3948)
-
=> CIAS30-3948: fix

.github/workflows/ci.yml, Gemfile.lock, app/jobs/user_session_jobs/schedule_daily_messages_job.rb
=> SMS_FIXES: changed schedule job execution time

config/application.rb
- Sidekiq is now working again
=> CIAS30 Restore missing config after rails upgrade

app/channels/notification_channel.rb, app/controllers/v1/live_chat/conversations_controller.rb, app/controllers/v1/pings_controller.rb, config/routes.rb
- [CIAS30-3980](https://htdevelopers.atlassian.net/browse/CIAS30-3980)
-
=> [CIAS30-3980] Navigators are being logged out on production

app/services/api/hfhs/authentication.rb
- [CIAS30-3992](https://htdevelopers.atlassian.net/browse/CIAS30-3992)
-
=> [CIAS30-3992] Fix HF authentication

config/environments/production.rb
=> [DEBUG] set tu debug lvl of logs

app/models/question/narrator/block/speech.rb, app/services/v1/audio_service.rb
- [CIAS30-4019](https://htdevelopers.atlassian.net/browse/CIAS30-4019)
-
=> [CIAS30-4019] Add guard to audio service
